function New-HealthReport {
    <#
    .SYNOPSIS
        Generates a standalone, responsive HTML system health dashboard.
    .DESCRIPTION
        Collects real-time telemetry from Get-LaptopHealth and builds a formatted HTML report.
    #>
    [CmdletBinding()]
    param(
        [string]$OutputPath,
        [switch]$NoOpen
    )

    $reportsDir = Join-Path $HOME "LaptopToolkit\Reports"
    if (-not (Test-Path $reportsDir)) { New-Item -ItemType Directory -Path $reportsDir -Force | Out-Null }

    if (-not $OutputPath) {
        $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
        $OutputPath = Join-Path $reportsDir "SystemHealth-Report_$timestamp.html"
    }

    $health = Get-LaptopHealth -PassThru

    $volRows = ""
    foreach ($v in $health.Volumes) {
        $volRows += "<tr><td>$($v.DriveLetter)</td><td>$($v.Label)</td><td>$($v.FreeGB) GB</td><td>$($v.TotalGB) GB</td><td>$($v.PercentFree)%</td></tr>"
    }

    $batStr = if ($health.Battery.Percent -ne $null) { "$($health.Battery.Percent)% ($($health.Battery.Status))" } else { "N/A (AC Only)" }

    $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LaptopToolkit - System Health Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0f172a; color: #f8fafc; margin: 0; padding: 2rem; }
        .container { max-width: 900px; margin: 0 auto; }
        .header { border-bottom: 2px solid #334155; padding-bottom: 1rem; margin-bottom: 2rem; }
        .header h1 { margin: 0; color: #38bdf8; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
        .card { background: #1e293b; padding: 1.5rem; border-radius: 8px; border: 1px solid #334155; }
        .card h3 { margin: 0 0 0.5rem 0; font-size: 0.875rem; color: #94a3b8; text-transform: uppercase; }
        .card .value { font-size: 1.75rem; font-weight: bold; color: #f1f5f9; }
        table { width: 100%; border-collapse: collapse; margin-top: 1rem; background: #1e293b; border-radius: 8px; overflow: hidden; }
        th, td { padding: 0.75rem 1rem; text-align: left; }
        th { background: #334155; color: #38bdf8; font-size: 0.875rem; }
        tr:nth-child(even) { background: #162032; }
        .footer { margin-top: 2rem; text-align: center; color: #64748b; font-size: 0.875rem; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>System Health Dashboard</h1>
            <p>Host: <b>$($health.ComputerName)</b> | OS: <b>$($health.OSCaption) (Build $($health.OSBuild))</b> | Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")</p>
        </div>
        <div class="grid">
            <div class="card">
                <h3>System Uptime</h3>
                <div class="value">$($health.Uptime.Days)d $($health.Uptime.Hours)h</div>
            </div>
            <div class="card">
                <h3>CPU Load</h3>
                <div class="value">$($health.CpuLoadPct)%</div>
            </div>
            <div class="card">
                <h3>RAM Utilization</h3>
                <div class="value">$($health.RamUsedPct)%</div>
                <small style="color: #94a3b8;">$($health.UsedRamGB) / $($health.TotalRamGB) GB</small>
            </div>
            <div class="card">
                <h3>Battery Status</h3>
                <div class="value">$batStr</div>
            </div>
        </div>
        <h2>Storage Volumes</h2>
        <table>
            <thead>
                <tr><th>Drive</th><th>Label</th><th>Free Space</th><th>Total Space</th><th>% Free</th></tr>
            </thead>
            <tbody>
                $volRows
            </tbody>
        </table>
        <div class="footer">
            <p>Generated by LaptopToolkit Open Source Suite.</p>
        </div>
    </div>
</body>
</html>
"@

    Set-Content -Path $OutputPath -Value $html
    Write-Host "Report created at: $OutputPath" -ForegroundColor Green
    Write-ToolkitLog "Generated HTML health report: $OutputPath" "INFO"

    if (-not $NoOpen) {
        Start-Process $OutputPath
    }
}
